name: duckdbless_reqs
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Run duckdbless setup
      run: |
         chmod +x ./scripts/duckdb-less_packages.sh
         ./scripts/duckdb-less_packages.sh
         git config --global user.email "actions@users.noreply.github.com"
         git config user.email "$(git log -n 1 --pretty=format:%ae)"
         git diff-index --quiet HEAD || (echo "Attempting to commit changes" && git commit -am 'lint with black' && git push -f)
      shell: bash
