name: Postgres tests
on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pg_splink_ci:
        image: postgres
        env:
          POSTGRES_USER: splinkognito
          POSTGRES_PASSWORD: splink123!
          POSTGRES_DB: splink_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    name: Run tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest -v --durations=0 -m "postgres_only" tests/
