name: Spark tests
on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # pyspark < 4 does not support python 3.12
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Run tests with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies and altair directly
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest -v --durations=0 -m "spark_only" tests/
