name: Run splink_demos tutorial notebooks

on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - splink/**
      - docs/demos/tutorials/**
      - pyproject.toml
      - "poetry.lock"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    name: Run tutorial notebooks with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root
          poetry run pip install -e .

      - name: Install additional requirements
        run: poetry run pip install -r docs/demos/data/demos_requirements.txt

      - name: Modify Notebooks to reduce data size
        run: python scripts/reduce_notebook_runtime.py

      - name: Run tutorial notebooks
        run: |
          poetry run pytest -vv --nbmake -n=auto --nbmake-kernel=python3 docs/demos/tutorials/*ipynb
