name: Run splink_demos tutorial notebooks

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: "moj-analytical-services/splink_demos"
          ref: master
          path: "splink_demos/"

      - name: Install environment and check notebooks
        run: |
            cd splink_demos
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install ..
            grep -v "splink==" requirements.txt > temp && mv temp requirements.txt
            pip install -r requirements.txt
            python -m pytest --nbmake --nbmake-kernel=python3 0[0-6]_*ipynb


