name: Run splink example notebooks

on:
  pull_request:
    branches:
      - master
      - "**dev"
    paths:
      - "splink/**"
      - "docs/demos/examples/**"
      - "!docs/demos/examples/examples_index.md"
      - "pyproject.toml"
      - "poetry.lock"
  workflow_dispatch:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        test-group: ["duckdb", "spark", "sqlite"]
    name: Test ${{ matrix.test-group }} notebooks with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry using pipx
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-root
          poetry run pip install -e .

      - name: Install additional requirements from demos_requirements.txt
        run: poetry run pip install -r docs/demos/data/demos_requirements.txt

      - name: Modify Notebooks to reduce data size
        run: python scripts/reduce_notebook_runtime.py

      - name: Test ${{ matrix.test-group }} example notebooks with pytest
        run: |
          poetry run pytest -vv --nbmake -n=auto --nbmake-kernel=python3 --durations=0 docs/demos/examples/${{ matrix.test-group }}/*ipynb
